//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPhoneNeywork
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ATS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATS()
        {
            this.Subscribers = new HashSet<Subscribers>();
            this.Price_List = new HashSet<Price_List>();
        }
    
        public int Код_АТС { get; set; }
        public string Название { get; set; }
        public string Вид { get; set; }
        public int Город { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Кол_во_абонентов { get; set; }
        public string Картинка { get; set; }

        public decimal? CityPrice
        {
            get
            {
                return Price_List.FirstOrDefault()?.Цена_на_городские_звонки;
            }
        }
        public decimal? MezhPrice
        {
            get
            {
                return Price_List.FirstOrDefault()?.Цена_на_межгородные_звонки;
            }
        }

        public string CityToString
        {
            get
            {
                return City?.Название_города ?? "неизвестен";
            }
        }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribers> Subscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_List> Price_List { get; set; }
    }
}
