//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPhoneNeywork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call_Log
    {
        public int Код_Звонка { get; set; }
        public int Код_Абонента_Отправителя { get; set; }
        public Nullable<int> Код_Абонента_Получателя { get; set; }
        public System.DateTime Дата_звонка { get; set; }
        public System.TimeSpan Время_начала_звонка { get; set; }
        public System.TimeSpan Время_окончания_звонка { get; set; }
        public bool Межгородный_звонок { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
        public virtual Subscribers Subscribers1 { get; set; }
    }
}
