//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPhoneNeywork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_List
    {
        public int Код_Прайс { get; set; }
        public int Код_АТС { get; set; }
        public decimal Цена_на_городские_звонки { get; set; }
        public decimal Цена_на_межгородные_звонки { get; set; }
    
        public virtual ATS ATS { get; set; }
    }
}
