//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPhoneNeywork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_Billing
    {
        public int Код_Абонентской_Платы { get; set; }
        public int Код_Абонента { get; set; }
        public int Месяц { get; set; }
        public int Год { get; set; }
        public int Количество_минут_на_городские_звонки { get; set; }
        public int Количество_минут_на_межгородные_звонки { get; set; }
        public decimal Стоимость { get; set; }
        public decimal Сумма_льготы { get; set; }
        public Nullable<decimal> Общая_стоимость { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
    }
}
